# Generated by Django 4.2.5 on 2023-11-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_technician_phone_1_alter_technician_phone_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="push_token",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
