# Generated by Django 4.2.5 on 2023-10-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complain_technician'),
        ('customers', '0002_machinetype_status_technician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
