# Generated by Django 4.2.5 on 2023-10-06 04:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_delete_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='manager_mobile_no',
            field=models.CharField(max_length=265, unique=True),
        ),
    ]
