# Generated by Django 4.2.5 on 2023-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_alter_machine_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="complain_limit",
        ),
        migrations.AddField(
            model_name="machine",
            name="complain_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="notify_on",
            field=models.IntegerField(
                blank=True, help_text="Notify on x Months Completed", null=True
            ),
        ),
    ]
