# Generated by Django 4.2.5 on 2023-10-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0007_remove_customer_complain_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accountant_mobile_no",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="accountant_name",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
