# Generated by Django 4.2.5 on 2023-11-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_customer_accountant_mobile_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="warranty_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
