# Generated by Django 4.2.5 on 2023-12-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_alter_customer_company_mobile_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
