# Generated by Django 4.2.5 on 2023-10-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_machinetype_status_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('issue', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'All'), (1, 'New'), (2, 'Pending'), (3, 'Running'), (4, 'Completed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.machine')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.technician')),
            ],
        ),
    ]
