# Generated by Django 4.2.5 on 2023-10-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_technician'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.technician'),
        ),
    ]
