# Generated by Django 4.2.5 on 2023-10-07 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_technician'),
        ('complaints', '0002_alter_complain_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('Genuine', 'Genuine'), ('Fake', 'Fake')], max_length=50)),
                ('challan', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('signature', models.CharField(max_length=255)),
                ('alignment', models.BooleanField(default=False)),
                ('ampere', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('water_filter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.complain')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.technician')),
            ],
        ),
    ]
