# Generated by Django 4.2.5 on 2023-10-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0004_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
