# Generated by Django 4.2.5 on 2023-10-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0007_service_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="end_date",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="start_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
