# Generated by Django 4.2.5 on 2023-10-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complainoutcome'),
        ('complaints', '0009_alter_service_status'),
    ]

    operations = [
    ]
