# Generated by Django 4.2.5 on 2023-10-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0010_merge_0003_complainoutcome_0009_alter_service_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainoutcome",
            name="alignment",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="complainoutcome",
            name="ampere",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="complainoutcome",
            name="challan",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="complainoutcome",
            name="temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="complainoutcome",
            name="voltage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="complainoutcome",
            name="water_filter",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Completed")], default=1
            ),
        ),
    ]
