# Generated by Django 4.2.5 on 2023-10-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0012_alter_complain_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="complainoutcome",
            name="watt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
