# Generated by Django 4.2.5 on 2023-10-27 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_complainoutcome_watt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainoutcome',
            name='signature',
            field=models.ImageField(upload_to='signature'),
        ),
    ]
