# Generated by Django 4.2.5 on 2023-10-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "complaints",
            "0014_service_solution_date_service_solution_technician_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="solution_technician",
            new_name="completed_by",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="solution_date",
            new_name="completed_date",
        ),
    ]
