# Generated by Django 4.2.5 on 2023-12-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0015_rename_solution_technician_service_completed_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainoutcome",
            name="signature",
            field=models.ImageField(blank=True, null=True, upload_to="signature"),
        ),
    ]
